#
# Copyright (C) 2017 Wind River Systems, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.
#

# System vendor
IOT_VENDOR: Wind River Systems
IOT_PRODUCT: Device Cloud
IOT_PRODUCT_SHORT: device-cloud
IOT_LIBRARY_NAME: iot
IOT_UTILITIES_NAME: iotutils
IOT_DESCRIPTION_SUMMARY: Wind River Systems' Internet of Things Solution

# Limits
IOT_ACTION_MAX: 255
IOT_ACTION_STACK_MAX: 3
IOT_ACTION_QUEUE_MAX: 10
IOT_ALARM_STACK_MAX: 3
IOT_ALARM_MAX: 255
IOT_OPTION_MAX: 20
IOT_PARAMETER_MAX: 7
IOT_SAMPLE_MAX: 10
IOT_TELEMETRY_STACK_MAX: 3
IOT_TELEMETRY_MAX: 255
IOT_WORKER_THREADS: 5

# Helper applications
IOT_TARGET_UPDATE: "iot-update"
IOT_TARGET_RELAY: "iot-relay"

# Default directories
IOT_DEFAULT_DIR_CONFIG: "/etc/iot"
IOT_DEFAULT_DIR_RUNTIME: "/var/lib/iot"

# Default file names
IOT_DEFAULT_FILE_CONFIG: "iot-connect"
IOT_DEFAULT_FILE_CONFIG_EXT: ".cfg"
IOT_DEFAULT_FILE_DEVICE_ID: "device_id"
IOT_DEFAULT_FILE_DEVICE_MANAGER: "iot.cfg"

# Default paths
IOT_BIN_DIR: "bin"

# Plugin options
IOT_PLUGIN_MAX: 5
IOT_PLUGIN_BUILTIN:
  - tr50: on

# User for running service
IOT_USER: "iot"
IOT_GROUP: "iot"

# default actions for device manager
IOT_DEFAULT_ENABLE_AGENT_RESET: true
IOT_DEFAULT_ENABLE_AGENT_QUIT: true
IOT_DEFAULT_ENABLE_DECOMMISSION_DEVICE: true
IOT_DEFAULT_ENABLE_DEVICE_REBOOT: true
IOT_DEFAULT_ENABLE_DEVICE_SHUTDOWN: true
IOT_DEFAULT_ENABLE_DUMP_LOG_FILES: true
IOT_DEFAULT_ENABLE_FILE_TRANSFERS: true
IOT_DEFAULT_ENABLE_REMOTE_LOGIN: true
IOT_DEFAULT_ENABLE_RESTORE_FACTORY_IMAGES: false
IOT_DEFAULT_ENABLE_SOFTWARE_UPDATE: true
IOT_DEFAULT_ENABLE_PING: true

# default settings for device manager
IOT_DEFAULT_ENABLE_PERSISTENT_ACTIONS: true
IOT_DEFAULT_UPLOAD_REMOVE_ON_SUCCESS: true

# default ssl CA bundle
IOT_DEFAULT_CERT_PATH: "/etc/ssl/certs/ca-certificates.crt"

IOT_UPDATE_LOGFILE: "iot_install_updates.log"

IOT_CONTROL_TARGET: "iot-control"

# number of seconds to wait before rebooting
IOT_REBOOT_DELAY: 5

