# System vendor
IOT_VENDOR: Wind River Systems
IOT_PRODUCT: Helix Device Cloud
IOT_PRODUCT_SHORT: hdc
IOT_LIBRARY_NAME: iot

# Library version
IOT_VERSION: 2.Next
IOT_VERSION_MAJOR: 2
IOT_VERSION_MINOR: 4
IOT_VERSION_PATCH: 0
IOT_VERSION_TWEAK: 0

# Limits
IOT_ACTION_MAX: 255
IOT_ACTION_STACK_MAX: 3
IOT_ACTION_QUEUE_MAX: 10
IOT_ALARM_STACK_MAX: 3
IOT_ALARM_MAX: 255
IOT_OPTION_MAX: 20
IOT_PARAMETER_MAX: 7
IOT_SAMPLE_MAX: 10
IOT_TELEMETRY_STACK_MAX: 3
IOT_TELEMETRY_MAX: 255
IOT_WORKER_THREADS: 5

# Helper applications
IOT_TARGET_UPDATE: "iot-update"

# Default directories
IOT_DEFAULT_DIR_CONFIG: "/etc/iot"
IOT_DEFAULT_DIR_RUNTIME: "/var/lib/iot"

# Default file names
IOT_DEFAULT_FILE_CONFIG: "iot-connect"
IOT_DEFAULT_FILE_CONFIG_EXT: ".cfg"
IOT_DEFAULT_FILE_DEVICE_ID: "device_id"
IOT_DEFAULT_FILE_DEVICE_MANAGER: "iot.cfg"

# Default paths
IOT_BIN_DIR: "bin"

# Plugin options
IOT_PLUGIN_MAX: 5
IOT_PLUGIN_BUILTIN:
  - tr50: on

# User for running service
IOT_USER: "iot"

# default actions for device manager
IOT_DEFAULT_ENABLE_AGENT_RESET: true
IOT_DEFAULT_ENABLE_DECOMMISSION_DEVICE: true
IOT_DEFAULT_ENABLE_DEVICE_REBOOT: true
IOT_DEFAULT_ENABLE_DEVICE_SHUTDOWN: true
IOT_DEFAULT_ENABLE_DUMP_LOG_FILES: true
IOT_DEFAULT_ENABLE_FILE_TRANSFERS: true
IOT_DEFAULT_ENABLE_REMOTE_LOGIN: true
IOT_DEFAULT_ENABLE_RESTORE_FACTORY_IMAGES: false
IOT_DEFAULT_ENABLE_SOFTWARE_UPDATE: true

# default settings for device manager
IOT_DEFAULT_ENABLE_PERSISTENT_ACTIONS: true
IOT_DEFAULT_ENABLE_AUTOMATION_TEST_ON_ANDROID: false
IOT_DEFAULT_UPLOAD_REMOVE_ON_SUCCESS: true

# default ssl CA bundle
IOT_DEFAULT_CERT_PATH: "/etc/ssl/certs/ca-certificates.crt"

IOT_UPDATE_LOGFILE: "iot_install_updates.log"

IOT_CONTROL_TARGET: "iot-control"

# number of seconds to wait before rebooting
IOT_REBOOT_DELAY: 5

